# Blog settings
permalink: /blog/:title

# Notes settings
permalink: /note/:title

# My variables
name: Zeove'blog
description: 偶尔写写，吐槽下生活，分享点自己觉得有意思的东西。
url: https://zeove.com
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
